import { NextResponse } from "next/server";
import { getProject, updateProject } from "@/lib/db";
import { createZipBuffer } from "@/lib/utils/zip";

type RouteContext = { params: Promise<{ id: string }> };

function generateSixFiles(project: {
  title: string;
  brief: string;
  id: string;
}): Record<string, string> {
  const now = new Date().toISOString().split("T")[0]!;
  return {
    "01-project-overview.md": `# ${project.title}\n\n**Generated:** ${now}\n\n## Brief\n\n${project.brief || "No brief provided."}\n\n## Status\n\nInitial project created via OXZI.\n`,
    "02-architecture.md": `# Architecture\n\n*This file was auto-generated by OXZI. Edit it as the project evolves.*\n\n**Project:** ${project.title}\n\n## Tech Stack\n\n- Framework: Next.js\n- Language: TypeScript\n- Styling: Tailwind CSS\n\n## High-Level Design\n\n(TBD)\n`,
    "03-ui-visual-context.md": `# UI / Visual Context\n\n**Project:** ${project.title}\n\n## Design Direction\n\n(TBD — visual direction is established during the discovery and design phase.)\n`,
    "04-code-standards.md": `# Code Standards\n\n**Project:** ${project.title}\n\n## Guidelines\n\n- Use strict TypeScript throughout\n- Components go under \`src/\`\n- Tests co-located or in \`__tests__/\`\n- Follow the existing project conventions\n`,
    "05-ai-workflow-rules.md": `# AI Workflow Rules\n\n**Project:** ${project.title}\n\n## Agent Instructions\n\n- Never modify protected files\n- Always run validation after changes\n- Follow the project's established patterns\n`,
    "06-progress-tracker.md": `# Progress Tracker\n\n**Project:** ${project.title}\n\n| Date | Milestone | Status |\n|------|-----------|--------|\n| ${now} | Project created | ✅ |\n`,
  };
}

export async function POST(_request: Request, context: RouteContext) {
  const { id } = await context.params;
  const project = getProject(id);

  if (!project) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 });
  }

  try {
    const files = generateSixFiles(project);
    const entries = Object.entries(files).map(([name, content]) => ({
      path: name,
      content,
    }));

    const zipBuffer = await createZipBuffer(entries);

    updateProject(id, { generatedFiles: files });

    return new NextResponse(new Uint8Array(zipBuffer), {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${encodeURIComponent(project.title)}-oxzi-files.zip"`,
        "Content-Length": zipBuffer.length.toString(),
      },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to generate files";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
